### PR TITLE
add templates for local ensemble observer and solver

### LINKED ISSUE #3: Update jcb templates for local ensemble observer and solver jobs
g-w issue [#2415](https://github.com/NOAA-EMC/global-workflow/issues/2415) adds jedi local ensemble observer and solver jobs. Templates are needed for the new observer and solver jobs.  This issue is opened to document the addition of these templates to jcb-algorithms

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR adds two local ensemble DA templates
- `local_ensemble_da_observer.yaml.j2`
- `local_ensemble_da_solver.yaml.j2`

The first runs the lgetkf in observer mode.  The second runs the lgetkf in solver mode.  

Resolves #3

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@TravisElless-NOAA and @SamuelDegelia-NOAA , this PR adds algorithm templates to run lgetkf in observer or solver modes.  This PR has been tested as part of g-w PR [#2833](https://github.com/NOAA-EMC/global-workflow/pull/2833) and GDASApp PR [#1252](https://github.com/NOAA-EMC/GDASApp/pull/1252).

If either of you have time, can you review these changes?

**Review by SamuelDegelia-NOAA — APPROVED** [review]
I am not familiar yet with JCB so I cannot comment too much on the structure of the templates. 

I did want to ask about `do posterior observer` though. You have it set to false by default. I have also been disabling this since the posterior hofx can be very slow given that it is computed for all of the modulated members too. Do you or @TravisElless-NOAA have any plans to produce any diagnostics for the ensemble analyses? 

Other than that question, the yamls look good to me!

**Comment by RussTreadon-NOAA** [comment]
@SamuelDegelia-NOAA , we will certainly want/need to generate diagnostics as we set up and check out the cycling system.  My thoughts are to generate diagnostics after the fact and not as part of the cycled system given how much additional time it adds to the job.  Hence setting the default to `.false.`.  

Another reason to set the default to `.false.` is that this is likely the option we will use in operations.  We are, however, a long, long way from operations.  The default can be changed to `.true.` and `.false.` set elsewhere.  

What do we (you, @TravisElless-NOAA , and I) want?

**Comment by TravisElless-NOAA** [comment]
For the `do posterior observer` flag conversation, my two cents are to keep the default as `.false.`. In the current target solver configuration, setting this process to `.true.` would force us to run the observer on all members using the Halo distribution. Previous global tests from @RussTreadon-NOAA and myself have shown running the observer in this configuration (even with the linear observer on) for large data types (e.g., the ~775,000 observation atms case) is currently not feasible. I also like the forward thinking consideration that `.false.` is the likely operational configuration, for at least the global, and not having to worry about a namelist parameter flag getting accidentally deleted or something causing the system to become unusable.

**Comment by SamuelDegelia-NOAA** [comment]
Thanks @RussTreadon-NOAA and @TravisElless-NOAA for the input - I am in agreement with both of you. When using `do posterior observer: true` for our 12km, 30-member MPAS-JEDI case with ~400k obs, it adds an additional 15-min of runtime. Definitely not feasible. I think my plan going forward is to do a separate run of `mpasjedi_enshofx.x` after GETKF, that way we can use RoundRobin distribution on just the original ensemble. It would be nice if there was a driver option in GETKF to just run the observer on the original ensemble, but that might be task for down the road. Thanks!

**Pull request merged**
