### PR TITLE
Add stat analysis template

### PR DESCRIPTION
**Pull request by kevindougherty-noaa**
Add stat analysis template jinja file used for stat analysis job in global workflow.

### CODE REVIEW

**Comment by danholdaway** [comment]
For now you need to create a branch with the same name in the jcb repo to get the CI to pass. You don't have to make a PR, but you have to push a branch with the same name. 

Since this new algo involves obs spaces I think you should add a section for it here: https://github.com/NOAA-EMC/jcb-algorithms/blob/develop/observer_components.yaml This ensures you only end up with the parts of the observer YAMLs that you actually need.

**Review by danholdaway — CHANGES_REQUESTED** [review]
Thanks for adding. A couple of minor comments.

**Comment by kevindougherty-noaa** [comment]
@danholdaway Thank you for reviewing Dan, just pushed a branch in jcb. Do you mind expanding on your second point from above? I am not quite sure I fully understand what you are asking. Thank you!

**Comment by danholdaway** [comment]
Seeing your jcb-gdas branch perhaps this isn't relevant. Since you aren't using the main observation YAML files but creating new ones in a new stats directory. So this is good to go.

**Review by danholdaway — APPROVED** [review]

**Pull request merged**
