### PR TITLE
Add more CI to GW-CI

### PR DESCRIPTION
**Pull request by DavidNew-NOAA**
This PR is a companion to [#1365](https://github.com/NOAA-EMC/GDASApp/pull/1365). It makes inclusion of the testing blocks in the algorithm templates dependent on a ```do_testing``` parameter that will be set in the JCB base YAML.

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by danholdaway** [comment]
This is probably not an ideal way to change things. You need to have do_testing in every single application of JCB whether it's true or false. Better would have been:

```
{% if do_testing | default(false) %}
```

FYI the testing of jcb is working now so we shouldn't ignore failures. I suspect that if we tried to run GDASapp with this we'd see a lot of failures because of the need to add `do_testing` to all the jcb-base YAMLS.

**Comment by danholdaway** [comment]
Before I fix things, what was wrong with using `{% if test_reference_filename is defined %}`? We now have a mixture of this approach and do_testing across the YAMLs so we should pick one. I'm fine with do_testing if that's the way we want to go.

**Comment by DavidNew-NOAA** [comment]
@danholdaway See my comment here https://github.com/NOAA-EMC/jcb-gdas/pull/42#issuecomment-2470753580

**Comment by danholdaway** [comment]
OK. Then I will apply the same to all the YAMLs in jcb-algo.

**Comment by DavidNew-NOAA** [comment]
This PR was merged a bit prematurely, I was hoping to have your eyes on it before that happened.

**Comment by danholdaway** [comment]
No problem. Straightforward fix I think. And apologies that I did not review sooner.

**Pull request merged**
